config/routes.rb
Bundlemoney::Application.routes.draw do
  resources :invitations, only: :index
  root :to => "home#index"
  devise_for :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  has_many :invitations, :class_name => self.class.to_s, :as => :invited_by

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     @inviter = User.find(current_user.invited_by) if user_signed_in? && current_user.invited_by
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_filter authenticate_user!
  def index
    @invitations = current_user.invitations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/home/index.html.haml
%p
  - if user_signed_in?
    - if @inviter
      %p
        Your payments will reward
        %h3
          = @inviter.email
      %hr
    %p Get Reward from invites
    = link_to 'Invite', new_user_invitation_path
  - else
    = link_to 'Register', new_user_registration_path

app/views/invitations/_invitation.html.haml
.row
  .span12
    = inviation.email

app/views/invitations/index.html.haml
- if @invitations
  - @invitations.each do |invitation|
    = render 'invitation', invitation: invitation

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Bundlemoney", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to (current_user.name.blank? ? current_user.email : current_user.name), edit_user_registration_path
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
    %li
      = link_to 'Invites', invitations_path
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Bundlemoney"
      %meta{:content => content_for?(:description) ? yield(:description) : "Bundlemoney", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main